### ISSUE TITLE
Feature: User can generate a list of question cards

### ISSUE THREAD

**Issue by rosemary-liang** [rosemary-liu/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can generate a list of trivia question cards.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Trivia enthusiasts will want to practice their trivia skills.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![MacBook - Question Grid](https://user-images.githubusercontent.com/95596680/155813217-cc5f9569-7dcb-41e0-bce3-6bafec150dec.png)

![iPhone - Question Grid](https://user-images.githubusercontent.com/95596680/155813253-b791d217-1a34-4ddf-978c-20af71853cb0.png)

## ✅ Task List

-  Commit checklist for tasks needed to complete the feature.

  - [x] Add the header div containing the app name and navbar.
  - [x] Add anchor tags to Favorites and Questions Correct in navbar.
  - [x] Add the question card grid, link each card to a question.
  - [x] Get data upon first load.
  - [x] Create data object to store API response. Create unique Id's.
  - [x] Make sure that click targets are either `<a>` or `<button>` elements.
  - [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
