### ISSUE TITLE
Feature: User can generate new set of questions after all questions are answered

### ISSUE THREAD

**Issue by rosemary-liang** [rosemary-liu/ajax-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

After all questions have been answered, user will be able to see the final score and be able to click a button to generate a new set of trivia questions.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After all questions have been answered,  the user will see a modal that shows the final score as well as a button to "Try More Questions". Once the button is clicked, the old questions will be wiped, and a new set of questions will be loaded and ready for answering.  If user clicks in the model overlay instead of clicking "Try More Questions", then user will return to question grid view. User can click on any card to bring up the "Try More Questions" prompt again.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![MacBook - All Q's answered - reset (1)](https://user-images.githubusercontent.com/95596680/156819152-a1b34886-3160-408c-8b31-11fcf2afc4f4.png)
![iPhone - All Q's Answered - reset (1)](https://user-images.githubusercontent.com/95596680/156819160-92c244b0-7120-4ccf-822f-57f40cb09dfa.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create `resetAll` function to:
     - [x] Reset `data.nextEntryId` to 1.
     - [x] Reset data.clues to an empty array.
     - [x] Reset score to 0.
     - [x] call `getClues()`.
- [x] Create new modal view to appear after last question has been answered.
- [x] Show the final score in the modal.
- [x] Add event listener to Try More Questions button in the modal to run resetAll() on 'click'. 
- [x] Confirm that data object is properly reset with new clues.
- [x] Confirm that after the Try More Questions button is clicked, the grid visually resets and will display the new clues when cards are clicked.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
