### ISSUE TITLE
Design Update: Full CSS design overhaul for a fresh look

### ISSUE THREAD

**Issue by rosemary-liang** [rosemary-liu/ajax-project#14]
## ⚙️ Feature

> ##### Which feature is affected by this update?

All features are affected and the entire app will look different, but maintain the same functionality.

## 📐 Plan

> ##### Summary of the technical approach to be taken.

Use CSS to achieve the look and design of the new wireframes.

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

![MacBook - Question Grid - STYLED](https://user-images.githubusercontent.com/95596680/156935056-5ad0ceef-a2bd-458e-b935-df8dd6999af3.png)

![MacBook - Q1 Question selected (hover) - STYLED](https://user-images.githubusercontent.com/95596680/156935059-c75f5497-62e5-4d60-8426-b515737e65e6.png)

![MacBook - Q1 Modal Question - STYLED](https://user-images.githubusercontent.com/95596680/156935064-3711494f-9131-4277-a8d2-d408187f93cd.png)

![MacBook - Q1 Modal Answer - STYLED](https://user-images.githubusercontent.com/95596680/156935069-48a7a046-7bb0-4593-8814-efcc94349fce.png)

![MacBook - Q1 Question answered - STYLED](https://user-images.githubusercontent.com/95596680/156935076-fb76f5c8-0f15-467a-b4f8-a6f384faa243.png)

![MacBook - Q1 Already Answered - STYLED](https://user-images.githubusercontent.com/95596680/156935078-f5d30c73-2952-42a7-ab1e-69495d23d052.png)

![MacBook - Favorites - STYLED (1)](https://user-images.githubusercontent.com/95596680/156935079-64388240-ef49-4dbc-8295-c8604409d320.png)

![MacBook - Questions Correct - STYLED](https://user-images.githubusercontent.com/95596680/156935083-aa94aa76-22d1-440f-9f4d-f671743e49f1.png)

![MacBook - All Q's answered - STYLED](https://user-images.githubusercontent.com/95596680/156935088-d604b4ff-f466-4029-becf-aa6bf95970ef.png)

![image](https://user-images.githubusercontent.com/95596680/157307074-eddf7834-5abf-40e8-b714-dbc735971477.png)

![image](https://user-images.githubusercontent.com/95596680/157307085-e74c71ad-9657-43d3-9400-1491b8a84c03.png)

![image](https://user-images.githubusercontent.com/95596680/157307643-605d9ce7-e7e8-44dc-87ab-2febb124d6c7.png)

![image](https://user-images.githubusercontent.com/95596680/157307104-cfe26b01-3b0c-412e-9d6d-13e35780ce66.png)

## ✅ Task List

- **Commit checklist for tasks needed to complete the feature.**

  - [x] Update CSS styling of header and nav bar to match the wireframe.
  - [x] Update CSS styling of grid view to match the wireframe.
       - [x] Update the clue:hover CSS styling
       - [x] Update styling of clue buttons that were already answered
  - [x] Update CSS styling of the clue display
       - [x] Remove the modal, and change the modal to a new `data-view: clue`.
       - [x] Change the existing `data-modal` attributes in the modal to `data-clue-view` with the following values:
            - [x] question, click-to-see-answer, answer, return, reset
       - [x] Update JavaScript functions to add hidden class when view is not active.
            - [x] Remove event listener from modal
            - [x] Change openModal function to navToClue
            - [x] Remove handleModal function 
            - [x] Remove closeModal function
            - [x] Add See Answer button and add event listener to run showAnswer() upon click.
            - [x] Remove event listener from non-modal click, and reassign the click event listener to a back button
       - [x] Add 'Question 1' header to the clue display.
       - [x] Update CSS styling for answer display and 'Yes' and 'No' buttons
  - [x] Update CSS styling for 'Question Already Answered'.
       - [x] Change 'Return to Questions' to a simple back button
  - [x] Update CSS styling for Favorites page
       - [x] Update title placement
       - [x] Change Return to Questions to back button
       - [x] Update render function to add "Question 1" header to the top of each card. Add CSS styling to that line.
  - [x] Update CSS styling for Questions Correct page
       - [x] Update title placement
       - [x] Change Return to Questions to back button
       - [x] Update render function to add 'Question 1' header to the top of each card. Add CSS styling to that line.
  - [x] Update CSS styling for 'All Questions Answered' view by removing modal and using `data-view: all-questions-answered`.
  - [x] Make sure that click targets are either `<a>` or `<button>` elements.
  - [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.

- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
