### ISSUE TITLE
Refactor: Change JavaScript from ES5 to ES6

### ISSUE THREAD

**Issue by rosemary-liang** [rosemary-liu/ajax-project#17]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] Change variable declarations to use keywords let and const
- [x] Change functions to be arrow functions
- [x] Change object dot notation to destructuring
- [x] Change strings to template literals
- [x] Check conditional statements and make sure subsequent conditions are not direct opposites of the first. 
     - [x] If they are, they should only say "else" with no condition. 
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
