### ISSUE TITLE
Feature 2: User can click on a card to view and answer a question.

### ISSUE THREAD

**Issue by rosemary-liang** [rosemary-liu/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to select a card from the question grid to view a question, answer the question in their head, and check to see if their answer is correct. User will also be able to mark whether he or she answered correctly.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to select one card from the grid of 9 cards and open a modal to view a question, or "hint". 

If user clicks outside the card, and on the modal background overlay, it will return to the questions view and close the modal.

If user clicks on the card, it will display the answer. The user can then answer a prompt indicating whether his or her answer was correct. The modal will close upon selection. 

If correct, the number of questions answered and the score will be adjusted appropriately according to the points for that question. 

All answered cards will turn gray and if clicked, will return "Question already answered" and user will be able to select "Return to Questions" button to close the modal.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![MacBook - Q1 Modal Question](https://user-images.githubusercontent.com/95596680/156237949-f5e7f039-0430-4322-b56d-adff3cbf704e.png) 
![MacBook - Q1 Modal Answer](https://user-images.githubusercontent.com/95596680/156237977-fded7f0c-55bf-4679-a40b-11f03a8bfea7.png)
![MacBook - Q1 Question answered](https://user-images.githubusercontent.com/95596680/156238031-c57f9346-c86f-4941-8f83-c3b2107d49f6.png)
![MacBook - Q1 Already answered](https://user-images.githubusercontent.com/95596680/156238037-53db5ed3-974b-4466-9c8f-b9b5a245068f.png)

![iPhone - Q1 Modal Question](https://user-images.githubusercontent.com/95596680/156238064-350adb80-cc2c-45e2-85d8-a26d353bca24.png) ![iPhone - Q1 Modal Answer](https://user-images.githubusercontent.com/95596680/156238077-de3a14b1-c319-4582-856d-36e45712de63.png)
![iPhone - Q1 Question Answered](https://user-images.githubusercontent.com/95596680/156238091-965c095f-67f1-4dd1-a13a-b1d69cf66c24.png) ![iPhone - Q1 already answered](https://user-images.githubusercontent.com/95596680/156238101-7b30e3bd-d928-439e-8be3-260ae16a3569.png)

## ✅ Task List

The user will be able to select one card from the grid of 9 cards and open a modal to view a question, or "hint". 
If user clicks outside the card, and on the modal background overlay, it will return to the questions view and close the modal.
If user clicks on the card, it will display the answer. The user can then answer a prompt indicating whether his or her answer was correct. The modal will close upon selection. 
If correct, The number of questions answered and the score will be adjusted appropriately according to the points for that question. 
All answered cards will turn gray and if clicked, will return "Question already answered" and user will be able to select "Return to Questions" button to close the modal.

- **Commit checklist for tasks needed to complete the feature.**
  - [x] Add event listener so that modal will open upon 'click' event occurring in the clues-container.
  - [x] Confirm modal populates with data from corresponding object in clues array with matching entryId.
  - [x] Add event listener on background overlay, which will return to questions view upon 'click'.
  - [x] Add custom attribute to include `data-modal: question`, `data-modal: answer`, `data-modal: answered`. Add `view` and `hidden` classes to modal elements to correspond with their custom attributes.
  - [x] Add event listener on modal card, which will display answer view upon 'click'.
  - [x] Add event listener on "YES" and "NO" buttons. 
     - [x] If either button is clicked, update the array item's `completed` property value as "yes". 
     - [x] If "YES" is clicked, update `data.score` and `data.questionsCorrect` array. Close the modal.
     - [x] If "YES" is clicked, update header to reflect Questions Correct and Score.
     - [x] If "NO" is clicked, close the modal.
  - [x] Verify that all cards with the completed property value yes are gray.
  - [x] Reset the views nodeList so that appropriate items are hidden and vice versa
     - [x] When completed cards are clicked, open modal and show button to return to questions
     - [x] Add event listener on return to questions button and confirm it resets the modal view.
  - [x] #5
     - [x] Change background fill to yellow for favorited and gray for not favorited.
     - [x] Update the clue's `favorite` property.
  - [x] Verify that updates to the data object are saved to local storage on page reload.
  - [x] Make sure that click targets are either `<a>` or `<button>` elements.
  - [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
