### ISSUE TITLE
Feature: User can view questions answered correctly.

### ISSUE THREAD

**Issue by rosemary-liang** [rosemary-liu/ajax-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to click the Questions Correct link in the header to view the cards of questions that were answered correctly. Users will be able to swap back to question grid view by clicking Back to Questions.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click on "Questions Correct" link in the header and view the cards of questions that were answered correctly. Users can scroll through the list and return to the question grid by clicking "Back to Questions" link.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![MacBook - Questions Correct (1)](https://user-images.githubusercontent.com/95596680/156478388-b6d29d60-2d7b-4bc2-b665-10138a5f577d.png)

![iPhone - Questions Correct (1)](https://user-images.githubusercontent.com/95596680/156480542-85e26046-1c0e-4539-ac8c-b11e0153733f.png)

## ✅ Task List
- **Commit checklist for tasks needed to complete the feature.**

  - [x] Set up custom attributes to include `data-view: grid` and `data-view: questions-correct`.
  - [x] Set up DOM tree for question card.
  - [x] Create function to render DOM tree for all items in data.clues with `correct: true`
  - [x] Format the cards to match the wireframes.
  - [x] Set up title and "Back to Questions" link formatting.
  - [x] Set up view swapping between the grid and questions-correct.
       - [x] Confirm "Back to Questions" link and "Questions Correct" link execute view swapping.
  - [x] Format Questions Correct in header to blue font to indicate that it is current view.
  - [x] Make sure that click targets are either `<a>` or `<button>` elements.
  - [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
  
  
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
