### ISSUE TITLE
Feature: User can view favorite questions

### ISSUE THREAD

**Issue by rosemary-liang** [rosemary-liu/ajax-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to click the Favorites link in the header to view the cards of questions that were favorited. Users will be able to swap back to question grid view by clicking Back to Questions.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click on "Favorites" link in the header and view the cards of questions that were favorited. Users can scroll through the list and return to the question grid by clicking "Back to Questions" link. Users can favorite or un-favorite questions that appear in the Favorites view by clicking on the star icon.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![MacBook - Favorites](https://user-images.githubusercontent.com/95596680/156643068-d99d1795-fc29-4684-9456-89016ae6993d.png)

![iPhone - Favorites](https://user-images.githubusercontent.com/95596680/156643077-49db2ca4-578b-45f7-a22f-27af625f7501.png)

## ✅ Task List

- **Commit checklist for tasks needed to complete the feature.**
   - [x] Set up custom attributes to include `data-view: favorites`.
   - [x] Create function to render DOM tree for all items in data.clues with `favorite: true`
   - [x] Format the cards to match the wireframes.
   - [x] Add functionality to star icon to allow user to favorite and un-favorite cards that appear. 
       - [x] The 'favorite' property of `data.clues` should be updated accordingly.
       - [x] Star icon appears yellow unless user chooses to un-favorite the card
   - [x] Add star functionality of color and updating of `data.clues.favorite` to the cards on the Questions Correct view.
   - [x] Set up title and "Back to Questions" link formatting.
   - [x] Set up view swapping between the grid and questions-correct.
       - [x] Confirm "Back to Questions" link and "Favorites" link execute view swapping.
   - [x] Format Questions Correct in header to blue font to indicate that it is current view.
   - [x] User can see changes to Favorites without refreshing the page.
   - [x] Make sure that click targets are either `<a>` or `<button>` elements.
   - [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
  
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
